eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    catalogservice: /catalogs/**
    orderservice: /orders/**
    accountservice: /accounts/**

# we can change the default to service id to make
# the change specific to a single service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500 

#Ribbon time out => setting ribbon timeout
catalogservice:
  ribbon:
    ReadTimeout: 7000
   

# for actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
#Rabbbit mq brocker config data for dynamic refresh of configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest