tracer:
   property: "I AM THE DEFAULT"
spring:
   data:
     mongodb:
        host: "localhost"
        port: "27017"

# for actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"
		
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/