tracer:
   property: I AM THE DEFAULT
spring:
   data:
     mongodb:
        host: localhost
        port: 27017
   rabbitmq:
     host: localhost
     port: 5672
     username: guest
     password: guest
   boot:
     admin:
       client:
         url: http://localhost:9090
         username: admin
         password: client

# for actuator end points
management:
  endpoints:
    web:
      exposure:
      include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/