tracer:
  property: "I AM THE DEFAULT"
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: true
    eureka:
      instance:
        preferIpAddress: true
      client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

# Global Unified Configuration
hysterix:
  command:
    default:
      execution:
        isolation:
        # Change to THREAD, and the rest of the configuration at the beginning of SEMAPHORE can be removed
        strategy: THREAD
        thread:
          # By default 1000
          timeoutInMilliseconds: 2000
