tracer:
   property: "I AM THE DEV"
logging:
   level:
      com:
        sivalabs: "debug"

spring:
  datasource:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      url: "jdbc:mysql://localhost:3306/test?useSSL=false"
      username: "root"
      password: "admin"
      initialization-mode: "always"
  jpa:
    hibernate.ddl-auto: "update"
    show-sql: "true"
  servlet:
    multipart:
      enabled: "true"
      file-size-threshold: "2KB"
      max-file-size: "215MB"


server:
  forward-headers-strategy: "framework"

#file.upload.dir=/Users/wontgn/Documents/Product_images

# Feign Configuration
feign:
   hystrix:
      enabled: "true"
	  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# for actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"