tracer:
  property: "I AM THE DEV"
logging:
  level:
    com:
      sivalabs: "debug"

spring:
  datasource:
     driver-class-name: "com.mysql.cj.jdbc.Driver"
     url: "jdbc:mysql://localhost:3306/test?useSSL=false"
     username: "root"
     password: "admin"
     initialization-mode: "always"
  jpa:
     hibernate:
        ddl-auto: "update"
     show-sql: "true"
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: client
	 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
	  
# for actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"